export type Role = 'student' | 'admin';

export interface Company {
  id: string;
  name: string;
  logo: string; // emoji placeholder
  isGalaSponsor: boolean;
  isOnlineRecruitment: boolean;
  // Fields visible to both
  fields: string[];
  skills: string[];
  benefits: {
    allowance: string;
    meals: string;
    housing: string;
  };
  totalSlots: number;
  availableSlots: number;
  // Admin-only fields
  contactName: string;
  contactPhone: string;
  contactEmail: string;
  website: string;
  industry: string;
}

export interface Registration {
  id: string;
  studentId: string;
  studentName: string;
  companyId: string;
  companyName: string;
  registeredAt: string;
  isExternal: boolean;
}

export const INITIAL_COMPANIES: Company[] = [
  {
    id: "real_1",
    name: "CÔNG TY CỔ PHẦN SẢN XUẤT VÀ DỊCH VỤ LEANMAC",
    logo: "🏭",
    isGalaSponsor: false,
    isOnlineRecruitment: true,
    fields: ["Tự Động Hóa & PLC","Thiết Kế Cơ Khí & CAD/CAM","AI & Machine Learning","Robot Công Nghiệp"],
    skills: ["PLC/SCADA","CAD/SolidWorks","Tiếng Anh"],
    benefits: {
      allowance: "Hỗ trợ chi phí cơ bản",
      meals: "Có hỗ trợ bữa ăn",
      housing: "Không bố trí, tự túc",
    },
    totalSlots: 6,
    availableSlots: 6,
    contactName: "Phạm Thị Ngọc Bích",
    contactPhone: "0393176268",
    contactEmail: "Chưa cập nhật",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_2",
    name: "CÔNG TY CỔ PHẦN THIẾT BỊ VÀ GIẢI PHÁP CƠ KHÍ AUTOMECH",
    logo: "🔧",
    isGalaSponsor: true,
    isOnlineRecruitment: true,
    fields: ["Tự Động Hóa & PLC","Robot Công Nghiệp","Thiết Kế Cơ Khí & CAD/CAM","Vận Hành Sản Xuất"],
    skills: ["PLC/SCADA","C/C++","CAD/SolidWorks","Tiếng Anh"],
    benefits: {
      allowance: "Có phụ cấp cố định hàng tháng",
      meals: "Có hỗ trợ bữa ăn",
      housing: "Không bố trí, tự túc",
    },
    totalSlots: 30,
    availableSlots: 30,
    contactName: "Trần Thị Thanh",
    contactPhone: "0989888160",
    contactEmail: "thanhtt@automech.vn",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_3",
    name: "Công ty Cổ phần Kim Khí Thăng Long",
    logo: "⚙️",
    isGalaSponsor: true,
    isOnlineRecruitment: true,
    fields: ["Vận Hành Sản Xuất"],
    skills: ["Hiểu biết cơ bản về thiết bị"],
    benefits: {
      allowance: "Có phụ cấp cố định hàng tháng",
      meals: "Có hỗ trợ bữa ăn",
      housing: "Có bố trí ký túc xá",
    },
    totalSlots: 50,
    availableSlots: 50,
    contactName: "Hoàng Huy Chung",
    contactPhone: "0983006998",
    contactEmail: "hoanghuychung@gmail.com",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_4",
    name: "Công ty TNHH TM& DV Laser Việt Nhật",
    logo: "🤖",
    isGalaSponsor: true,
    isOnlineRecruitment: true,
    fields: ["Thiết Kế Cơ Khí & CAD/CAM","Robot Công Nghiệp","Vận Hành Sản Xuất","Tự Động Hóa & PLC"],
    skills: ["CAD/SolidWorks","Tiếng Anh","Có kỹ năng tiếng anh giao ti"],
    benefits: {
      allowance: "Có phụ cấp cố định hàng tháng",
      meals: "Có hỗ trợ bữa ăn",
      housing: "Có bố trí ký túc xá",
    },
    totalSlots: 15,
    availableSlots: 15,
    contactName: "Kiều Anh",
    contactPhone: "0982.763.666",
    contactEmail: "Anhkieu@laservietnhat.com.vn",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_5",
    name: "Công ty TNHH Phát Triển Thương Mại Minh Vũ",
    logo: "💡",
    isGalaSponsor: false,
    isOnlineRecruitment: true,
    fields: ["Robot Công Nghiệp","Tự Động Hóa & PLC","Thiết Kế Cơ Khí & CAD/CAM"],
    skills: ["PLC/SCADA","C/C++","CAD/SolidWorks","Kỹ năng thiết kế mạch điện t","Tiếng Anh"],
    benefits: {
      allowance: "Hỗ trợ chi phí cơ bản",
      meals: "Có hỗ trợ bữa ăn",
      housing: "Không bố trí, tự túc",
    },
    totalSlots: 10,
    availableSlots: 10,
    contactName: "Vũ Thái Sơn",
    contactPhone: "0968292834",
    contactEmail: "sale1.minhvu@gmail.com",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_6",
    name: "Unilever",
    logo: "🛠️",
    isGalaSponsor: false,
    isOnlineRecruitment: true,
    fields: ["Tự Động Hóa & PLC","IoT & Nhúng","Robot Công Nghiệp"],
    skills: ["PLC/SCADA","C/C++","Tiếng Anh","Có kỹ năng tiếng anh giao ti"],
    benefits: {
      allowance: "Có phụ cấp cố định hàng tháng",
      meals: "Có hỗ trợ bữa ăn",
      housing: "Không bố trí, tự túc",
    },
    totalSlots: 1,
    availableSlots: 1,
    contactName: "Nguyễn Minh Hăng",
    contactPhone: "0916261170",
    contactEmail: "nguyen-minh.hang@unilever.com",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_7",
    name: "Công ty TNHH Công nghệ máy văn phòng Kyocera Việt Nam",
    logo: "🔬",
    isGalaSponsor: true,
    isOnlineRecruitment: false,
    fields: ["Robot Công Nghiệp","Thiết Kế Cơ Khí & CAD/CAM","Điều khiển truyền động (Motion Cont","Công nghệ in 3D & Sản xuất đắp dần"],
    skills: ["CAD/SolidWorks","C/C++","Kỹ năng thiết kế mạch điện t","Tiếng Anh","Có kỹ năng tiếng anh giao ti"],
    benefits: {
      allowance: "Có phụ cấp cố định hàng tháng",
      meals: "Có hỗ trợ bữa ăn",
      housing: "Có bố trí ký túc xá",
    },
    totalSlots: 0,
    availableSlots: 0,
    contactName: "Đặng Anh Thơ",
    contactPhone: "0359494575",
    contactEmail: "tho.da@dtvn.kyocera.com",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_8",
    name: "Công ty cổ phần công nghiệp TCI",
    logo: "📡",
    isGalaSponsor: false,
    isOnlineRecruitment: true,
    fields: ["Tự Động Hóa & PLC","Robot Công Nghiệp","Thiết Kế Cơ Khí & CAD/CAM","Điều khiển truyền động (Motion Cont"],
    skills: ["PLC/SCADA","CAD/SolidWorks","Tiếng Anh","Ưu tiên sinh viên thành thảo"],
    benefits: {
      allowance: "Có phụ cấp cố định hàng tháng",
      meals: "Có hỗ trợ bữa ăn",
      housing: "Không bố trí, tự túc",
    },
    totalSlots: 2,
    availableSlots: 2,
    contactName: "Đào Văn Đồng",
    contactPhone: "0975795299",
    contactEmail: "dongdv@tci.vn",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_9",
    name: "CÔNG TY TNHH INNOVATION PRECISION VIỆT NAM",
    logo: "🏗️",
    isGalaSponsor: false,
    isOnlineRecruitment: true,
    fields: ["Tự Động Hóa & PLC","Thiết Kế Cơ Khí & CAD/CAM","Vận Hành Sản Xuất"],
    skills: ["PLC/SCADA","C/C++","CAD/SolidWorks","Tiếng Anh","Ưu tiên biết tiếng trung"],
    benefits: {
      allowance: "Có phụ cấp cố định hàng tháng",
      meals: "Có hỗ trợ bữa ăn",
      housing: "Không bố trí, tự túc",
    },
    totalSlots: 8,
    availableSlots: 8,
    contactName: "Đường Thị Trang",
    contactPhone: "0347846161",
    contactEmail: "Trang.dt@sdcxjt.com",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_10",
    name: "Công ty CP Thiết bị và Dịch vụ TCE",
    logo: "🚗",
    isGalaSponsor: false,
    isOnlineRecruitment: false,
    fields: [],
    skills: [],
    benefits: {
      allowance: "Chưa cung cấp",
      meals: "Chưa xác nhận",
      housing: "Chưa xác nhận",
    },
    totalSlots: 5,
    availableSlots: 5,
    contactName: "Đới Minh Diệp",
    contactPhone: "0969560686",
    contactEmail: "tuyendung@tce.net.vn",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_11",
    name: "Công ty Cổ phần Công nghệ và đầu tư INTECH",
    logo: "🔩",
    isGalaSponsor: true,
    isOnlineRecruitment: true,
    fields: ["Tự Động Hóa & PLC","IoT & Nhúng","Thiết Kế Cơ Khí & CAD/CAM","Vận Hành Sản Xuất"],
    skills: ["PLC/SCADA","C/C++","CAD/SolidWorks","Tiếng Anh"],
    benefits: {
      allowance: "Phụ cấp theo năng lực",
      meals: "Có hỗ trợ bữa ăn",
      housing: "Có bố trí ký túc xá",
    },
    totalSlots: 5,
    availableSlots: 5,
    contactName: "Nguyễn Thị Vân",
    contactPhone: "0982561613",
    contactEmail: "tuyendung.ho2@intechgroup.vn",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_12",
    name: "Công ty TNHH Daiwa Plastics Thăng Long",
    logo: "💻",
    isGalaSponsor: true,
    isOnlineRecruitment: true,
    fields: ["Tự Động Hóa & PLC","Robot Công Nghiệp","AI & Machine Learning"],
    skills: ["PLC/SCADA","C/C++","CAD/SolidWorks","Kỹ năng thiết kế mạch điện t","Tiếng Anh"],
    benefits: {
      allowance: "Có phụ cấp cố định hàng tháng",
      meals: "Có hỗ trợ bữa ăn",
      housing: "Không bố trí, tự túc",
    },
    totalSlots: 5,
    availableSlots: 5,
    contactName: "Tạ Đức Khôi",
    contactPhone: "0912097676",
    contactEmail: "khoi-td@daiwa-tl.com",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_13",
    name: "Công ty TNHH Điện tử Meiko Việt Nam",
    logo: "🌐",
    isGalaSponsor: true,
    isOnlineRecruitment: true,
    fields: ["Tự Động Hóa & PLC","IoT & Nhúng","Thiết Kế Cơ Khí & CAD/CAM","Robot Công Nghiệp"],
    skills: ["PLC/SCADA","C/C++","CAD/SolidWorks","Kỹ năng thiết kế mạch điện t","Có kỹ năng tiếng anh giao ti","Tiếng Anh"],
    benefits: {
      allowance: "Có phụ cấp cố định hàng tháng",
      meals: "Có hỗ trợ bữa ăn",
      housing: "Có bố trí ký túc xá",
    },
    totalSlots: 10,
    availableSlots: 10,
    contactName: "Nguyễn Đặng Duy",
    contactPhone: "0936293433 hoặc 0944806116",
    contactEmail: "duy.nguyendang@meiko-elec.com",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_14",
    name: "Công ty TNHH thiết bị HT Việt Nam",
    logo: "⚡",
    isGalaSponsor: false,
    isOnlineRecruitment: true,
    fields: ["Thiết Kế Cơ Khí & CAD/CAM","Tự Động Hóa & PLC","Vận Hành Sản Xuất","AI & Machine Learning"],
    skills: ["CAD/SolidWorks"],
    benefits: {
      allowance: "Phụ cấp theo năng lực",
      meals: "Có hỗ trợ bữa ăn",
      housing: "Không bố trí, tự túc",
    },
    totalSlots: 3,
    availableSlots: 3,
    contactName: "Hoàng Thị Minh Hằng",
    contactPhone: "+84 91 6511138",
    contactEmail: "Hcnsht@thietbiht.com",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_15",
    name: "Công ty Cổ phần Santomas Việt Nam",
    logo: "🎯",
    isGalaSponsor: false,
    isOnlineRecruitment: true,
    fields: ["Tự Động Hóa & PLC","AI & Machine Learning","Robot Công Nghiệp","Thiết Kế Cơ Khí & CAD/CAM"],
    skills: ["PLC/SCADA","Kỹ năng thiết kế mạch điện t","Có kỹ năng tiếng anh giao ti"],
    benefits: {
      allowance: "Có phụ cấp cố định hàng tháng",
      meals: "Có hỗ trợ bữa ăn",
      housing: "Không bố trí, tự túc",
    },
    totalSlots: 2,
    availableSlots: 2,
    contactName: "Hoàng Thị Thu",
    contactPhone: "0982537406",
    contactEmail: "thu.ht@santomas.com.vn",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_16",
    name: "Công ty TNHH Makino Việt Nam",
    logo: "🔭",
    isGalaSponsor: true,
    isOnlineRecruitment: true,
    fields: ["Robot Công Nghiệp","Tự Động Hóa & PLC","Thiết Kế Cơ Khí & CAD/CAM","Điều khiển truyền động (Motion Cont"],
    skills: ["PLC/SCADA","Tiếng Anh","CAD/SolidWorks"],
    benefits: {
      allowance: "Có phụ cấp cố định hàng tháng",
      meals: "Có hỗ trợ bữa ăn",
      housing: "Không bố trí, tự túc",
    },
    totalSlots: 5,
    availableSlots: 5,
    contactName: "Trần Đức Minh",
    contactPhone: "0983435455",
    contactEmail: "Ducminh.tran@makino.com.vn",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_17",
    name: "Công ty Cổ phần Công nghiệp TCI",
    logo: "📊",
    isGalaSponsor: true,
    isOnlineRecruitment: true,
    fields: ["Thiết Kế Cơ Khí & CAD/CAM","Điều khiển truyền động (Motion Cont","Tự Động Hóa & PLC","Robot Công Nghiệp"],
    skills: ["CAD/SolidWorks","Tiếng Anh","PLC/SCADA"],
    benefits: {
      allowance: "Có phụ cấp cố định hàng tháng",
      meals: "Có hỗ trợ bữa ăn",
      housing: "Không bố trí, tự túc",
    },
    totalSlots: 20,
    availableSlots: 20,
    contactName: "Tạ Thị Thu Hà",
    contactPhone: "0978733663",
    contactEmail: "hattt@tci.vn/ phuongntm@tci.vn",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_18",
    name: "Công ty TNHH Canon Việt Nam",
    logo: "🏢",
    isGalaSponsor: false,
    isOnlineRecruitment: true,
    fields: ["Tự Động Hóa & PLC","Robot Công Nghiệp","Thiết Kế Cơ Khí & CAD/CAM","Điều khiển truyền động (Motion Cont"],
    skills: ["PLC/SCADA","C/C++","CAD/SolidWorks","Kỹ năng thiết kế mạch điện t"],
    benefits: {
      allowance: "Có phụ cấp cố định hàng tháng",
      meals: "Có hỗ trợ bữa ăn",
      housing: "Có bố trí ký túc xá",
    },
    totalSlots: 50,
    availableSlots: 50,
    contactName: "Nguyễn Thị Thu (HR)",
    contactPhone: "0365309625",
    contactEmail: "thu.nguyen539@mail.canon",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_19",
    name: "Công ty tnhh Neweb Việt Nam(WNC)",
    logo: "🔌",
    isGalaSponsor: false,
    isOnlineRecruitment: false,
    fields: ["Vận Hành Sản Xuất","Tự Động Hóa & PLC","Kho , tự động hóa","Điều khiển truyền động (Motion Cont"],
    skills: ["Kỹ năng thiết kế mạch điện t"],
    benefits: {
      allowance: "Có phụ cấp cố định hàng tháng",
      meals: "Có hỗ trợ bữa ăn",
      housing: "Có bố trí ký túc xá",
    },
    totalSlots: 70,
    availableSlots: 70,
    contactName: "RUBY HR",
    contactPhone: "0985971246",
    contactEmail: "Ruby.pei@wnc.com.tw",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_20",
    name: "CÔNG TY TNHH PHẦN MỀM HICAS",
    logo: "🛒",
    isGalaSponsor: true,
    isOnlineRecruitment: true,
    fields: ["Thiết Kế Cơ Khí & CAD/CAM","AI & Machine Learning","Robot Công Nghiệp"],
    skills: ["C/C++","CAD/SolidWorks","Tiếng Anh","Có kỹ năng tiếng anh giao ti"],
    benefits: {
      allowance: "Phụ cấp theo năng lực",
      meals: "Không hỗ trợ",
      housing: "Không bố trí, tự túc",
    },
    totalSlots: 3,
    availableSlots: 3,
    contactName: "Võ Công Minh",
    contactPhone: "0983683620",
    contactEmail: "minh@hicas.co",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_21",
    name: "Công ty cổ phần hệ thống AIoT",
    logo: "🧪",
    isGalaSponsor: false,
    isOnlineRecruitment: true,
    fields: ["IoT & Nhúng","Điều khiển truyền động (Motion Cont","Robot Công Nghiệp","AI & Machine Learning"],
    skills: ["C/C++","Kỹ năng thiết kế mạch điện t"],
    benefits: {
      allowance: "Hiện tại chưa có chính sách hỗ trợ tài chính",
      meals: "Có hỗ trợ bữa ăn",
      housing: "Không bố trí, tự túc",
    },
    totalSlots: 4,
    availableSlots: 4,
    contactName: "Lê văn Hoan",
    contactPhone: "0839799889",
    contactEmail: "Hoanle@aiots.vn",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_22",
    name: "Công Ty Cổ Phần Croptex",
    logo: "🏆",
    isGalaSponsor: false,
    isOnlineRecruitment: true,
    fields: ["Robot Công Nghiệp","IoT & Nhúng","Thiết Kế Cơ Khí & CAD/CAM","Điều khiển truyền động (Motion Cont"],
    skills: ["CAD/SolidWorks","Kỹ năng thiết kế mạch điện t","PLC/SCADA","C/C++"],
    benefits: {
      allowance: "Phụ cấp theo năng lực",
      meals: "Có hỗ trợ bữa ăn",
      housing: "Không bố trí, tự túc",
    },
    totalSlots: 3,
    availableSlots: 3,
    contactName: "Lê Văn Linh",
    contactPhone: "0327340913",
    contactEmail: "buithutrang@croptex.vn",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_23",
    name: "Công ty TNHH Thuận Thành Nam Việt",
    logo: "🎮",
    isGalaSponsor: false,
    isOnlineRecruitment: false,
    fields: ["Thiết Kế Cơ Khí & CAD/CAM","Điều khiển truyền động (Motion Cont","AI & Machine Learning","Vận Hành Sản Xuất"],
    skills: ["CAD/SolidWorks"],
    benefits: {
      allowance: "Có phụ cấp cố định hàng tháng",
      meals: "Có hỗ trợ bữa ăn",
      housing: "Có bố trí ký túc xá",
    },
    totalSlots: 3,
    availableSlots: 3,
    contactName: "Nguyễn Văn Thùy",
    contactPhone: "0969577103",
    contactEmail: "thuy031997@gmail.com",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_24",
    name: "Tổng Công ty Sản xuất thiết bị Viettel",
    logo: "💼",
    isGalaSponsor: false,
    isOnlineRecruitment: true,
    fields: ["Thiết Kế Cơ Khí & CAD/CAM","Vận Hành Sản Xuất","Lập Trình Phần Mềm"],
    skills: ["CAD/SolidWorks","Kỹ năng thiết kế mạch điện t","Tiếng Anh","C/C++"],
    benefits: {
      allowance: "Có phụ cấp cố định hàng tháng",
      meals: "Có hỗ trợ bữa ăn",
      housing: "Có bố trí ký túc xá",
    },
    totalSlots: 30,
    availableSlots: 30,
    contactName: "Hồ Thanh Nga  Lê Thị Minh Nguyệt",
    contactPhone: "Hồ Thanh Nga - Chuyên viên nhân sự - SĐT: 0333.560.270Lê Thị Minh Nguyệt - Chuyên viên nhân sự - SĐT: 0968.669.966",
    contactEmail: "vmctuyendung@gmail.com",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_25",
    name: "Công ty Cổ phần Kim khí Thăng Long",
    logo: "📦",
    isGalaSponsor: true,
    isOnlineRecruitment: true,
    fields: ["Vận Hành Sản Xuất","Cơ khí chế tạo máy","Tự Động Hóa & PLC","Robot Công Nghiệp"],
    skills: ["Hiểu biết cơ bản về nguyên l"],
    benefits: {
      allowance: "Có phụ cấp cố định hàng tháng",
      meals: "Có hỗ trợ bữa ăn",
      housing: "Có bố trí ký túc xá",
    },
    totalSlots: 50,
    availableSlots: 50,
    contactName: "Hoàng Huy Chung",
    contactPhone: "0983006998",
    contactEmail: "hoanghuychung@gmail.com",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_26",
    name: "Công ty TNHH Thương mại quốc tế 3S Việt Nam",
    logo: "🔷",
    isGalaSponsor: false,
    isOnlineRecruitment: true,
    fields: ["Tự Động Hóa & PLC","Thiết Kế Cơ Khí & CAD/CAM","Điều khiển truyền động (Motion Cont","Vận Hành Sản Xuất"],
    skills: ["CAD/SolidWorks","Tiếng Anh","Có kỹ năng tiếng anh giao ti","C/C++","PLC/SCADA"],
    benefits: {
      allowance: "Có phụ cấp cố định hàng tháng",
      meals: "Có hỗ trợ bữa ăn",
      housing: "Không bố trí, tự túc",
    },
    totalSlots: 3,
    availableSlots: 3,
    contactName: "Nguyễn Thị Thu Huyền",
    contactPhone: "0986638545",
    contactEmail: "3svietnam@posi3s.com",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_27",
    name: "Công ty Cổ phần IL-SUNG TECH",
    logo: "🚀",
    isGalaSponsor: true,
    isOnlineRecruitment: true,
    fields: ["Vận Hành Sản Xuất","Robot Công Nghiệp","Tự Động Hóa & PLC"],
    skills: ["Không yêu cầu thêm chuyên mô"],
    benefits: {
      allowance: "Phụ cấp theo năng lực",
      meals: "Có hỗ trợ bữa ăn",
      housing: "Có bố trí ký túc xá",
    },
    totalSlots: 50,
    availableSlots: 50,
    contactName: "Nguyễn Tiến Thanh",
    contactPhone: "0869143888",
    contactEmail: "thanh.nt@il-sungtech.com",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_28",
    name: "Công ty TNHH MTV Thép VAS Nghi Sơn",
    logo: "🌿",
    isGalaSponsor: true,
    isOnlineRecruitment: true,
    fields: ["Tự Động Hóa & PLC","Thiết Kế Cơ Khí & CAD/CAM","Vận Hành Sản Xuất","AI & Machine Learning"],
    skills: ["PLC/SCADA","CAD/SolidWorks","Kỹ năng thiết kế mạch điện t","Tiếng Anh"],
    benefits: {
      allowance: "Có phụ cấp cố định hàng tháng",
      meals: "Có hỗ trợ bữa ăn",
      housing: "Có bố trí ký túc xá",
    },
    totalSlots: 20,
    availableSlots: 20,
    contactName: "Trần Thị Hồng",
    contactPhone: "0987803585",
    contactEmail: "hongtt@vassteel.vn",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_29",
    name: "Công ty TNHH Laird Việt Nam (Công ty con tại Việt Nam của công ty Qnity Electronics)",
    logo: "🔑",
    isGalaSponsor: false,
    isOnlineRecruitment: false,
    fields: ["Tự Động Hóa & PLC","Vận Hành Sản Xuất","AI & Machine Learning"],
    skills: ["Tiếng Anh","Có kỹ năng tiếng anh giao ti","PLC/SCADA"],
    benefits: {
      allowance: "Có phụ cấp cố định hàng tháng",
      meals: "Có hỗ trợ bữa ăn",
      housing: "Không bố trí, tự túc",
    },
    totalSlots: 10,
    availableSlots: 10,
    contactName: "Trần Ngọc Tú",
    contactPhone: "0944681886",
    contactEmail: "Brian.tran@qnityelectronics.com",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_30",
    name: "Công ty TNHH Nestlé Việt nam",
    logo: "🏥",
    isGalaSponsor: true,
    isOnlineRecruitment: true,
    fields: ["AI & Machine Learning","Tự Động Hóa & PLC","Vận Hành Sản Xuất"],
    skills: ["Có kỹ năng tiếng anh giao ti","CAD/SolidWorks","PLC/SCADA","Tiếng Anh"],
    benefits: {
      allowance: "Có phụ cấp cố định hàng tháng",
      meals: "Có hỗ trợ bữa ăn",
      housing: "Không bố trí, tự túc",
    },
    totalSlots: 6,
    availableSlots: 6,
    contactName: "Trương Thị Phương Thảo",
    contactPhone: "0968855517",
    contactEmail: "truongthiphuong.thao@vn.nestle.com",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_31",
    name: "STEAM for Vietnam Foundation",
    logo: "📐",
    isGalaSponsor: true,
    isOnlineRecruitment: true,
    fields: ["Thiết Kế Cơ Khí & CAD/CAM","Điều khiển truyền động (Motion Cont","Công nghệ in 3D & Sản xuất đắp dần","IoT & Nhúng"],
    skills: ["C/C++","CAD/SolidWorks","Kỹ năng thiết kế mạch điện t","Tiếng Anh"],
    benefits: {
      allowance: "Hiện tại chưa có chính sách hỗ trợ tài chính",
      meals: "Không hỗ trợ",
      housing: "Không bố trí, tự túc",
    },
    totalSlots: 4,
    availableSlots: 4,
    contactName: "Joy Vũ",
    contactPhone: "0349363293",
    contactEmail: "joy@steamforvietnam.org",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
  {
    id: "real_32",
    name: "Công ty TNHH Sản xuất đồ gia dụng Sunhouse",
    logo: "🎛️",
    isGalaSponsor: false,
    isOnlineRecruitment: true,
    fields: ["Tự Động Hóa & PLC","IoT & Nhúng","Thiết Kế Cơ Khí & CAD/CAM","Điều khiển truyền động (Motion Cont"],
    skills: ["CAD/SolidWorks","Kỹ năng thiết kế mạch điện t","Tiếng Anh"],
    benefits: {
      allowance: "Phụ cấp theo năng lực",
      meals: "Có hỗ trợ bữa ăn",
      housing: "Không bố trí, tự túc",
    },
    totalSlots: 7,
    availableSlots: 7,
    contactName: "Tạ Thị Ngọc Mai",
    contactPhone: "0373539379",
    contactEmail: "maittn@sunhouse.com.vn",
    website: '#',
    industry: 'Cơ Điện Tử & Tự Động Hóa',
  },
];

export const INITIAL_REGISTRATIONS: Registration[] = [];
